Update for v2.08.100.00.

diff --git a/common-functions b/common-functions
--- a/common-functions
+++ b/common-functions
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # Copyright (c) 2014-2018, Linaro Ltd. All rights reserved.
-# Copyright (c) 2020, Ampere Computing LLC. All rights reserved.
+# Copyright (c) 2020, Ampere Computing LLC.
 #
 # SPDX-License-Identifier: ISC
 #
@@ -234,6 +234,7 @@ function get_atf_tools
     if [ -e "${ATF_TOOLS}/tools/cert_create/cert_create" ]; then
         return 0
     fi
+    ATF_TOOL_TAG="v2.6"
     rm -fr ${ATF_TOOLS}
     mkdir -p ${ATF_TOOLS}
     cd ${ATF_TOOLS}
@@ -241,15 +242,30 @@ function get_atf_tools
     git remote add origin -f https://github.com/ARM-software/arm-trusted-firmware.git
     git config core.sparseCheckout true
     echo -ne "include/tools_share\nmake_helpers\ntools/cert_create\ntools/fiptool" > .git/info/sparse-checkout
-    git -C . checkout --track origin/master
+    git -C . checkout tags/${ATF_TOOL_TAG} -b ${ATF_TOOL_TAG}
     make -C tools/cert_create -j $NUM_THREADS CRTTOOL=cert_create
     make -C tools/fiptool -j $NUM_THREADS FIPTOOL=fiptool
     return 0
 }
 
+function get_efitools
+{
+    EFI_TOOLS="$1"
+    EFITOOLS_VER="$2"
+    rm -fr ${EFI_TOOLS}
+    mkdir -p ${EFI_TOOLS}
+    cd ${EFI_TOOLS}
+    git init
+    git remote add origin -f https://github.com/vathpela/efitools.git
+    git config core.sparseCheckout true
+    git -C . checkout v${EFITOOLS_VER}
+    make cert-to-efi-sig-list sign-efi-sig-list
+    return 0
+}
+
 function check_golang
 {
-    GOLANG_VER=1.15.6
+    GOLANG_VER=$1
     GOLANG_ARCH=amd64
     GOLANG_INSTALL_DIR=${TOOLS_DIR}/toolchain
     echo "Checking golang ver ${GOLANG_VER}... build arch: ${BUILD_ARCH}"
@@ -373,5 +389,26 @@ function check_lzma_tool
     fi
     echo "ERROR: can't locate the lzma tool" >&2
     echo "       please install lzma tool" >&2
+    return 1
+}
+
+function check_efitools
+{
+    TOOLS_DIR="$1"
+    EFITOOLS_VER="$2"
+    if which sign-efi-sig-list >/dev/null 2>&1 && which cert-to-efi-sig-list >/dev/null 2>&1 && sign-efi-sig-list --version 2>/dev/null | grep ${EFITOOLS_VER}; then
+        echo "---> sign-efi-sig-list, cert-to-efi-sig-list"
+        return 0
+    fi
+    get_efitools ${TOOLS_DIR}/efitools ${EFITOOLS_VER}
+    mkdir -p ${TOOLS_DIR}/toolchain/efitools
+    cp -a ${TOOLS_DIR}/efitools/sign-efi-sig-list ${TOOLS_DIR}/toolchain/efitools
+    cp -a ${TOOLS_DIR}/efitools/cert-to-efi-sig-list ${TOOLS_DIR}/toolchain/efitools
+    if sign-efi-sig-list --version >/dev/null 2>&1 && cert-to-efi-sig-list --version >/dev/null 2>&1; then
+        rm -fr ${TOOLS_DIR}/efitools
+        return 0
+    fi
+    echo "ERROR: can't locate the efitools" >&2
+    echo "       please install efitools" >&2
     return 1
 }
